# 함수를 통한 행렬 생성

In [1]:
import numpy as np

In [8]:
# 0으로 채워진 행렬을 만든다
shape1 = np.zeros(3)
print(f'shape1 : {shape1}')

shape2 = np.zeros(3, dtype=int)
print(f'shape2 : {shape2}')

# (행의 개수, 열의 개수)
shape3 = np.zeros((3,2))
print(f'shape3 : {shape3}')

# (면의 개수, 행의 개수, 열의 개수)
shape4 = np.zeros((2,3,4))
print(f'shape4: {shape4}')

shape1 : [0. 0. 0.]
shape2 : [0 0 0]
shape3 : [[0. 0.]
 [0. 0.]
 [0. 0.]]
shape4: [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [11]:
# 1로 채워진 행렬
shape1 = np.ones(3)
print(f'shape1 : {shape1}')

shape2 = np.ones(3, dtype=int)
print(f'shape2 : {shape2}')

shape3 = np.ones((3,2))
print(f'shape3 : {shape3}')

shape4 = np.ones((2,3,4))
print(f'shape4 : {shape4}')

shape1 : [1. 1. 1.]
shape2 : [1 1 1]
shape3 : [[1. 1.]
 [1. 1.]
 [1. 1.]]
shape4 : [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [13]:
# 지정된 숫자로 채워진 행렬 생성
# (행렬정보, 채울 숫자)
shape1 = np.full(3,7)
print(f'shape1 : {shape1}')

shape2 = np.full((3, 2), 7)
print(f'shape2 : {shape2}')

shape3 = np.full((2, 3, 4), 7)
print(f'shape3 : {shape3}')

shape1 : [7 7 7]
shape2 : [[7 7]
 [7 7]
 [7 7]]
shape3 : [[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]


In [14]:
# NxN의 단위 행렬 생성
shape1 = np.eye(5)
print(f'shape1 : {shape1}')

shape1 : [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
# empty 함수 : 지정된 정보를 토대로 행렬을 만든다
# 값을 세팅하지 않기 때문에 행렬 생성 자체는 속도가 매우 빠르지만 값이 결정되어 있지 않기 때문에 쓰레기 값이 들어있다
# 반드시 값을 먼저 세팅해주고 사용해야 한다
shape1 = np.empty(3)
shape2 = np.empty((2, 3))
shape3 = np.empty((2, 3, 4))
print(f'shape1 : {shape1}')
print(f'shape2 : {shape2}')
print(f'shape3 : {shape3}')

shape1 : [7.74860419e-304 7.74860419e-304 7.74860419e-304]
shape2 : [[1. 1. 1.]
 [1. 1. 1.]]
shape3 : [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [19]:
# like 계열
# 지정된 리스트와 동일한 형태의 행렬을 만든다
# zeros_like
# ones_like
# full_like
# empty_like

list1 = [[1, 2, 3], [4, 5, 6]]

shape1 = np.array(list1)
shape2 = np.zeros_like(list1)
shape3 = np.ones_like(list1)
shape4 = np.full_like(list1,7)
shape5 = np.empty_like(list1)

print(f'shape1 : {shape1}')
print(f'shape2 : {shape2}')
print(f'shape3 : {shape3}')
print(f'shape4 : {shape4}')
print(f'shape5 : {shape5}')

shape1 : [[1 2 3]
 [4 5 6]]
shape2 : [[0 0 0]
 [0 0 0]]
shape3 : [[1 1 1]
 [1 1 1]]
shape4 : [[7 7 7]
 [7 7 7]]
shape5 : [[1 2 3]
 [4 5 6]]
