In [140]:
import pandas as pd

In [141]:
# Series 
s1 = pd.Series((10, 20, 30, 40, 50, 60, 70, 80, 90, 100))
print(f'{s1}')

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64


In [142]:
# Series에 포함된 데이터를 numpy 행렬 객체로 가져온다
print(f'{s1.values}')

[ 10  20  30  40  50  60  70  80  90 100]


In [143]:
dic = {
    2000 : 101, 2001 : 102, 2002 : 103,
    2003 : 104, 2004 : 105, 2005 : 106,
    2006 : 107, 2007 : 108, 2008 : 109
}
s2 = pd.Series(dic)
print(f'{s2}')

2000    101
2001    102
2002    103
2003    104
2004    105
2005    106
2006    107
2007    108
2008    109
dtype: int64


In [144]:
import numpy as np
# numpy 행렬을 이용해 DataFrame을 만든다.
a1 = np.random.randint(0, 10, (3, 3))
print('--- numpy 행렬 ---')
print(f'{a1}')

# 특서어 이름의 배열
title1 = ['A', 'B', 'C']
index = range(6, 9)
df1 = pd.DataFrame(a1, columns=title1, index=index)
print('--- numpy 행렬로 만든 DF ---')
print(f'{df1}')

--- numpy 행렬 ---
[[2 6 5]
 [2 0 6]
 [3 7 8]]
--- numpy 행렬로 만든 DF ---
   A  B  C
6  2  6  5
7  2  0  6
8  3  7  8


In [145]:
# 딕셔너리를 이용해 DF 만들기
dic1 = {
    'a' : [1, 2, 3],
    'b' : [4, 5, 6],
    'c' : [7, 8, 9]
}
df2 = pd.DataFrame(dic1)
print('--- 딕셔너리로 Df만들기 ---')
print(df2)

--- 딕셔너리로 Df만들기 ---
   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9


In [146]:
# 리스트를 활용해 Df 만들기
list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
df3 = pd.DataFrame(list2, columns=['A', 'B', 'C'])
print('--- list를 이용해 Df만들기 ---')
print(df3)

--- list를 이용해 Df만들기 ---
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [147]:
# 데이터 프레임 정보를 확인한다
title1 = ['A', 'B', 'C']
df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6]], columns=title1)
# (로우의 개수, Series의 개수)
print(df1.shape)
# 로우의 개수
print(len(df1))
# 컬럼 목록
print(df1.columns)

(2, 3)
2
Index(['A', 'B', 'C'], dtype='object')


In [148]:
dic = {
    'A' : [1, 4, 7],
    'B' : [2, 5, 8],
    'C' : [3, 6, 9]
}
df1 = pd.DataFrame(dic)

a1 = df1.iloc[0]
a2 = df1.loc[0]
a3 = df1.ix[0]
print(f'a1 : {a1}')
print(f'a2 : {a2}')
print(f'a3 : {a3}')

a1 : A    1
B    2
C    3
Name: 0, dtype: int64
a2 : A    1
B    2
C    3
Name: 0, dtype: int64
a3 : A    1
B    2
C    3
Name: 0, dtype: int64


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  # Remove the CWD from sys.path while we load stuff.


In [149]:
index=range(3, 8)
df2 = pd.DataFrame([1, 2, 3, 4, 5], index=index)
print(df2)
print(df2.ix[4]) # index 값이 4인 것을 가져옴
print(df2.iloc[4]) # 5번째인 것을 가져온다
print(df2.loc[4])# index 값이 4인 것을 가져옴

   0
3  1
4  2
5  3
6  4
7  5
0    2
Name: 4, dtype: int64
0    5
Name: 7, dtype: int64
0    2
Name: 4, dtype: int64


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.


In [150]:
index = ['A', 'B', 'C', 'D', 'E']
df3 = pd.DataFrame([1, 2, 3, 4, 5], index= index)

# 인덱스가 숫자로 구성되어 있다면 해당 인덱스 값의 데이터를 가져온다
# 인덱스가 문자로 되어있다면 2(실제로는 3번째)번째 값을 가져온다
print(df3)
print(df3.ix[2])
# 인덱스가 숫자로 되어 있지 않으면 오류발생
print(df3.loc[2])

   0
A  1
B  2
C  3
D  4
E  5
0    3
Name: C, dtype: int64


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  import sys


TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [2] of <class 'int'>

In [151]:
df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6]])
print(df1)

   0  1  2
0  1  2  3
1  4  5  6


In [152]:
df1.ix[0] = [10, 20, 30]
df1.loc[1] = [40, 50, 60]

print(df1)

    0   1   2
0  10  20  30
1  40  50  60


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [153]:
df1.ix[2] = [70, 80, 90]
df1.ix[3] = [100, 110, 120]

print(df1)

     0    1    2
0   10   20   30
1   40   50   60
2   70   80   90
3  100  110  120


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [154]:
df1.ix[10] = [1000, 2000, 3000]

print(df1)

       0     1     2
0     10    20    30
1     40    50    60
2     70    80    90
3    100   110   120
10  1000  2000  3000


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [155]:
df1.loc[20] = [2000, 3000, 4000]

print(df1)

       0     1     2
0     10    20    30
1     40    50    60
2     70    80    90
3    100   110   120
10  1000  2000  3000
20  2000  3000  4000


In [156]:
# 6(7번째) 로우가 없어서 오류가 발생한다
df1.iloc[6] = [5000, 6000, 7000]

print(df1)

IndexError: single positional indexer is out-of-bounds

In [157]:
df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6]])
df1.loc[10] = [10, 20, 30]
# 인덱스를 리셋한다
df1 = df1.reset_index(drop=True)
df1

0   1   2
0   1   2   3
1   4   5   6
2  10  20  30

In [158]:
# 로우 추가
df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6]])
df1 = df1.append([[7, 8, 9]])
df1 = df1.append([[10, 11, 12]])

df1 = df1.append([[13, 14, 15], [16, 17, 18]])

df1 = df1.reset_index(drop = True)
print(df1)

    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15
5  16  17  18


In [159]:
# 컬럼 추가
df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6]])
print(df1)
df1[4] = pd.Series([7, 8, 9]) # Series = Columns
print(df1)

# df1[4] : 컬럼에 대한 문법, df1.loc[4] : 로우에 대한 문법


   0  1  2
0  1  2  3
1  4  5  6
   0  1  2  4
0  1  2  3  7
1  4  5  6  8


In [160]:
title = ['A', 'B', 'C']
df1 = pd.DataFrame([[1, 2, 3],[4, 5, 6]], columns=title)
df1['K'] = pd.Series([4, 7])
df1

A  B  C  K
0  1  2  3  4
1  4  5  6  7

In [161]:
title = ['A', 'B', 'C']
df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6]], columns = title)
print(df1)

print(df1.loc[0]) # 0번째 로우의 값
print(df1['A']) # A 컬럼의 값
print(df1[['A','C']]) # A, C 컬럼의 값을 가져온다
print(df1[0:2]) # 0번째부터 2번째까지 컬럼의 값을 가져온다

   A  B  C
0  1  2  3
1  4  5  6
A    1
B    2
C    3
Name: 0, dtype: int64
0    1
1    4
Name: A, dtype: int64
   A  C
0  1  3
1  4  6
   A  B  C
0  1  2  3
1  4  5  6


In [162]:
# 0번 로우의 A 컬럼값
a1 = df1.loc[0, 'A']
print(f'a1 : {a1}')
# 1번 로우의 C 컬럼값
a2 = df1.loc[1, 'C']
print(f'a2 : {a2}')
# 0 ~ 1 로우의 B ~ C 컬럼 값
a3 = df1.loc[0:1, 'B':'C']
print(a3)
# 0 ~ 끝까지 로우의 A에서부터 끝까지 컬럼 값
a4 = df1.loc[0:, 'A':]
print(a4)

# 컬럼추가
df1.loc[:, 'D'] = pd.Series([7, 8, 9])
df1 = df1.reset_index()
df1

a1 : 1
a2 : 6
   B  C
0  2  3
1  5  6
   A  B  C
0  1  2  3
1  4  5  6


index  A  B  C  D
0      0  1  2  3  7
1      1  4  5  6  8

In [169]:
title = ['A', 'B', 'C']
df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6]], columns = title)
df1

#axis = 0 : 로우(기본), 1 : 컬럼
# df1 = df1.drop('A', axis =1)
# df1 # 원본을 지우는게 아님
# inplace = True : 원본에서 삭제, 생략했거나 False를 넣어주면 삭제된 df가 생성되어 반환된다.
df1.drop('A', axis =1, inplace = True)
df1

df1.drop(0, axis =0, inplace = True)
df1

B  C
1  5  6